services:
  - type: web
    name: securinets-hashcat-lab
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: INSTRUCTOR_KEY
        sync: false
